### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by teshe2008** [henok2424/SprKEd_API#3]
W20200625-08:02:01.177(3)? (STDERR) .meteor/packages/meteor-tool/.1.10.2.121ry7f.gueme++os.linux.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.linux.x86_64/dev_bundle/server-lib/node_modules/fibers/future.js:280
W20200625-08:02:01.204(3)? (STDERR) 						throw(ex);
W20200625-08:02:01.204(3)? (STDERR) 						^
W20200625-08:02:01.204(3)? (STDERR) 
W20200625-08:02:01.205(3)? (STDERR) [Error: "**Mutation**" defined in resolvers, but not in schema]

**Comment by henok2424** [comment]
I made some changes in resolver unit.js by removing Mutation to know its fixed.
